name: Format and test

on:
  push:
    branches:
      - master
  pull_request:
  workflow_call: 

concurrency:
  group: format-and-test
  cancel-in-progress: true

jobs:
  format:
    uses: nikita-volkov/haskell-hackage-lib-github-actions-workflows/.github/workflows/format.yaml@v4
    secrets: inherit
  
  check-cabal:
    uses: nikita-volkov/haskell-hackage-lib-github-actions-workflows/.github/workflows/check-cabal.yaml@v4
    secrets: inherit

  generate-docs:
    uses: nikita-volkov/haskell-hackage-lib-github-actions-workflows/.github/workflows/generate-docs.yaml@v4
    secrets: inherit

  build-with-ghc-8-8:
    uses: nikita-volkov/haskell-hackage-lib-github-actions-workflows/.github/workflows/build.yaml@v4
    secrets: inherit
    with:
      ghc: "8.8.1"
      skip-doctest: true
      skip-benchmarks: true
  
  build-with-latest:
    uses: nikita-volkov/haskell-hackage-lib-github-actions-workflows/.github/workflows/build.yaml@v4
    secrets: inherit
