name: Compile, test and check the docs

on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: on-push-to-master-or-pr
  cancel-in-progress: true

jobs:

  format:
    uses: nikita-volkov/haskell-hackage-lib-github-actions-workflows/.github/workflows/format.yaml@v3
    secrets: inherit

  check:
    uses: ./.github/workflows/check.yaml
    secrets: inherit
